### ISSUE TITLE
后台文章编辑使用tab无法缩进

### ISSUE THREAD

**Issue by vastroc** [lzxjack/blog-admin#1]
我这边通过游客方式进入编辑，使用tab是无法缩进的，不知道是不是因为是游客的原因

**Comment by lzxjack** [comment]
开发时没考虑到，按tab默认执行的是改变输入焦点的功能。待修复~

**Comment by Rockyzsu** [comment]
部署本地的时候，显示：src/components/TagCard/index.tsx:67:21 - error TS2339: Property 'all' does not exist on type 'ICommand

这个和react版本有关吗？

**Comment by lzxjack** [comment]
> 部署本地的时候，显示：src/components/TagCard/index.tsx:67:21 - error TS2339: Property 'all' does not exist on type 'ICommand
> 
> 这个和react版本有关吗？

和 React 版本没关系，是这个 @cloudbase/js-sdk 库的 TS 类型不完整。最新 main 分支用 any 修复。
